// FREQUENTLY ASKED QUESTIONS SECTION
// ----------------------------------

let faq = {

    // Page setup
    section: {parent: '', id: 'faq', widthPerc: 100, heightPerc: 50, content: '', cssScheme: 'transparent'},

    panels: [
        {parent: 'stacks', id: 'a', widthPerc: 98, heightPerc: 98, content: '', cssScheme: 'transparent'},
    ],

    boxes: [
        {parent: 'a', id: 'a1', widthPerc: 100, heightPerc: 20, cssScheme: 'whiteBox'},
        {parent: 'a', id: 'a2', widthPerc: 100, heightPerc: 20, cssScheme: 'whiteBox'},
        {parent: 'a', id: 'a3', widthPerc: 100, heightPerc: 20, cssScheme: 'whiteBox'},
        {parent: 'a', id: 'a4', widthPerc: 100, heightPerc: 20, cssScheme: 'whiteBox'},
    ],

    buttonRanges: [],
    buttons: [],
    page: '',

    setup: function() {
        this.page = new HeyPage(this.section, this.panels, this.boxes);

        this.page.boxes.a1.addTextBox('walletsFAQ', 'transparentLeft');
        this.page.boxes.a1.textBox.changeText('WALLETS FAQ:<br>o Click on WALLETS to load blockchain wallet data.<br>');

        this.page.boxes.a2.addTextBox('journeyFAQ', 'transparentLeft');
        this.page.boxes.a2.textBox.changeText('JOURNEY FAQ:<br>o Click on JOURNEY to view charts for loaded blockchain wallet data.<br>');

        this.page.boxes.a3.addTextBox('importsFAQ', 'transparentLeft');
        this.page.boxes.a3.textBox.changeText('IMPORTS FAQ:<br>o Click on IMPORT to load exchange trades and transactions.<br>');

        this.page.boxes.a4.addTextBox('stacksFAQ', 'transparentLeft');
        this.page.boxes.a4.textBox.changeText('STACKS FAQ:<br>o Click on STACKS to view your overall portfolio.<br>');
    },

    // Run the first time the site is visited
    initialSetup: function() {
        communication.message(this.initialMessage);
    },

    initialMessage: '<br><br><br><br><br>' +
        'Welcome to HeyStack!<br>' +
        '<br>' +
        'Please note that HeyStack is not professional software.<br>' +
        'Do not rely on any figures generated by this software for financial, investment, tax or any other decisions.<br>' +
        '<br>' +
        'HeyStack can be used to download historical data for Hive / Steem wallets and associated crypto prices.<br>' +
        'The volume of this data can be significant.<br>' +
        'Please use an appropriate wifi / broadband connection to manage your data allowances and avoid charges.<br>' +
        '<br>' +
        'Downloaded data is stored on your computer inside the browser using the IndexedDB database.<br>' +
        'Clearing your browser cache will remove this data.<br>' +
        '<br>' +
        'Testing has been carried out through the Chrome browser.<br>' +
        'Other browsers may not work.<br>' +
        '<br>' +
        'The vast majority of Hive and Steem financial transactions are catered for.<br>' +
        'However early transactions, such as mining, are not yet covered.<br>' +
        '<br>' +
        'Please click here to acknowledge this message.<br>' +
        '<br><br><br><br><br>',

    // Run opening tasks (fast only, no fetch, no aggregation)
    runOpeningTasks: async function() {
        // No tasks
    },

    // Run starting tasks (slow tasks)
    runTasks: async function() {
        // No tasks
    },

    // Run taks on switching away from section
    closeSwitchTasks: async function() {
        communication.messageOff();
    },
}
